name: Production
on:
  push:
    branches:
      - main
concurrency: off
jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest
    environment: production
    steps:

      - uses: actions/checkout@v3.3.0

      - uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - uses: actions/setup-node@v3.6.0
        with:
          node-version: '18.13.0'

      - shell: bash
        run: npm install -g -u aws-cdk@2.61.1 @angular/cli@15.1.2

      - shell: bash
        run: npm install

      - shell: bash
        run: ng build -c development

      - uses: actions/setup-python@v4.5.0
        with:
          python-version: '3.10'

      - shell: bash
        run: pip install -r requirements.txt

      - shell: bash
        run: cdk deploy
